#!/bin/bash
LOGLEVEL=info

npm install --prefix client && \
npm run bundle --prefix client && \
mvn package

if [ ! -z "$1" ]
then
  $LOGLEVEL=$1
fi
java -Dorg.slf4j.simpleLogger.defaultLogLevel=$LOGLEVEL -jar target/server-*.jar $*
